### ISSUE TITLE
Gets a mirrored video stream

### ISSUE THREAD

**Issue by Bloomingg** [livekit/livekit-react#29]
![image](https://user-images.githubusercontent.com/37789413/155714188-08d74b92-f8fb-4b5d-8339-da14be60b415.png)
When I use the virtual camera to make a video connection on my Mac, the local video stream is always mirrored. But it looks normal to everyone else.

**Comment by davidzhao** [comment]
hey @Bloomingg, the UI automatically mirrors camera feeds to yourself, but I can see how this would be a problem for virtual cameras.

can you get the facingMode value for the camera? perhaps we can tweak [this logic](https://github.com/livekit/livekit-react/blob/master/src/components/VideoRenderer.tsx#L57) to ensure it's only mirroring front-facing camera feeds.

**Comment by Bloomingg** [comment]
I get settings like that

**Comment by davidzhao** [comment]
thanks for sharing that.. it looks like it won't be possible to differentiate between a user-facing camera vs a virtual camera. there isn't much we can do here for the example app.

**Comment by Philzen** [comment]
Maybe we could expand the interface of `<VideoRenderer>`, allowing to override the default behaviour with an optional `isMirrored?: boolean` prop? 

https://github.com/livekit/livekit-react/blob/7a2a96fbe028b57df9c7b6bd8c1ea82bf003e536/packages/core/src/components/VideoRenderer.tsx#L5-L13

If set, it could then override the (otherwise feasible) default setting in

https://github.com/livekit/livekit-react/blob/7a2a96fbe028b57df9c7b6bd8c1ea82bf003e536/packages/core/src/components/VideoRenderer.tsx#L56-L57

**Comment by Philzen** [comment]
@Bloomingg #82 introduced a prop so you can override the default behaviour and take full control over mirroring now.

Maybe you or somebody want to contribute a checkbox to the example app that shows this prop in action?
