### ISSUE TITLE
I have some issues and doubts

### ISSUE THREAD

**Issue by GRNHACKER** [livekit/livekit-react#32]
Issues:

1. After successful connection between two user, i get the warning in server terminal that " channel congestion detected, updating channel capacity " and then connection gets poor.
2. When any user start screen sharing the quality suddenly started decreasing.

My doubts:

1.How can i set expiration of token using node js.
2.Can you please tell me the server requirement for 10,000 user at a time(both video audio).

**Comment by davidzhao** [comment]
Hi @GRNHACKER,

1. `channel congestion detected` is our congestion controller at work. this is when a participant's downstream bandwidth is limited.
2. I'm not sure what you mean, if you are talking about example app, that's because adaptive streaming is in play. When enabled, adaptive stream automatically adjusts resolution to match the size of the UI element

For information about access tokens, please refer to [the docs](https://docs.livekit.io/guides/access-tokens)
