### ISSUE TITLE
Unable to connect to insecure websocket from https

### ISSUE THREAD

**Issue by HDHChris** [livekit/livekit-react#45]
Hi, I deployed livekit server on a public network server, and then visited example app. Then the correct URL and token are configured. When I click the connect button, the following error is reported:

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/76725654/166666341-2bd57fe8-2007-4de9-8d2c-3ad39b342ad6.png">

How can I configure my livekit server to support WSS access? thank you

I tried to change the URL to WSS protocol, but the server connection error was reported:

<img width="539" alt="image" src="https://user-images.githubusercontent.com/76725654/166666124-cfa0de67-7c60-4311-8fd0-05f9bb25602f.png">

**Comment by lukasIO** [comment]
You will want to have an actual URL (instead of an IP) point to your livekit server in order to obtain a certificate for it.
Obtaining a valid certificate for your domain can be done in multiple ways (using caddy reverse proxy being one of the simplest).

More info here:
https://docs.livekit.io/deploy/vm/
https://docs.livekit.io/deploy#domain-ssl-certificates-and-load-balancer

For local testing purposes you can also run the example within the livekit-react repo locally. As long as your domain isn't on a `https` domain it will also work with `ws` instead of `wss`. Be aware that that's not a good solution in general and will only work in your internal/local network. 

Feel free to ask further questions on our community slack channel: https://join.slack.com/t/livekit-users/shared_invite/zt-rrdy5abr-5pZ1wW8pXEkiQxBzFiXPUg
